import { launch, startRun } from './lib.mjs';
const { browser, page } = await launch();
await page.goto('http://127.0.0.1:5173/?dev=1&gfx=low');
await startRun(page, 'RUN1');
await page.waitForTimeout(500);
await page.evaluate(() => { window.__sd.debug.teleport(32.6, 7.42); window.__sd.debug.setView(-2.63, 0); });
await page.waitForTimeout(300);
const a = await page.evaluate(() => window.__sd.state());
console.log('before', a.player.x.toFixed(2), a.player.z.toFixed(2), 'enemies near', JSON.stringify(a.enemies.filter((e) => Math.hypot(e.x - 32.6, e.z - 7.42) < 6).map((e) => [e.kind, e.state, e.alive, e.x.toFixed(1), e.z.toFixed(1), e.perched])));
await page.keyboard.down('KeyW');
await page.waitForTimeout(1500);
await page.keyboard.up('KeyW');
const b = await page.evaluate(() => window.__sd.state());
console.log('after', b.player.x.toFixed(2), b.player.z.toFixed(2), 'yaw', b.player.yaw.toFixed(2), 'mode', b.mode);
await browser.close();
